version: v1
plugins:
  # Use protoc-gen-go at v1.31.0
  - plugin: buf.build/protocolbuffers/go:v1.31.0
    out: internal/conf
    opt: paths=source_relative
  # Use the latest version of protoc-gen-validate
  - plugin:  buf.build/bufbuild/validate-go
    out: internal/conf
    opt:
      - paths=source_relative
